### PR TITLE
fixes towards a production deploy

### LINKED ISSUE #185: deploy Tapin staging server
cobuy-staging.tapin.nz

### PR DESCRIPTION
**Pull request by ahdinosaur**
closes #185

### CODE REVIEW

**Comment by ahdinosaur** [comment]
ready for review @iainkirkpatrick :blush:

**Comment by ahdinosaur** [comment]
this isn't 100% ready for production (#185) , but i reckon we should merge this pull request.

**Comment by ahdinosaur** [comment]
friendly review reminder ping @iainkirkpatrick

**Review by iainkirkpatrick — APPROVED** [review]
this looks good :)

**Pull request merged**
