### PR TITLE
chore/style offerings component

### LINKED ISSUE #86: style offerings component

### PR DESCRIPTION
**Pull request by gregorykan**
closes https://github.com/root-systems/cobuy/issues/86

### CODE REVIEW

**Review by ahdinosaur — APPROVED** [review]
rad

same deal with last pull request regarding responsive, but definitely a legit improvement.

**Comment by ahdinosaur** [comment]
screenshot:

cobuy-offerings

**Comment by ahdinosaur** [comment]
oh wait, sorry if i was too early on the review, just noticed this is still "in progress". :sweat_smile:

**Comment by gregorykan** [comment]
responsive-offerings

**Pull request merged**
