### PR TITLE
wip: dash the boards

### LINKED ISSUE #298: intuit the ux
this ticket is to take a minimal viable set of changes from https://github.com/root-systems/cobuy/issues/157 that can make the ux more intuitive

### PR DESCRIPTION
**Pull request by ahdinosaur**
closes #298 

TODO

- [x] move tasks to separate navigable page
- [x] dumb components
  - [x] OrderList
  - [x] OrderListItem
  - [x] Order
  - [x] OrderCreator
- [x] add order creator page
- [x] fetch all related order data
- [x] and get orders as a higher-level data abstraction
- [x] add orders page (order list and button to open order creator)
- [x] add order page
- [x] replace dashboard page with orders page
- [ ] ???

### CODE REVIEW

**Comment by michael-smith-nz** [comment]
Hey @ahdinosaur  This looks great! As mentioned on Slack and #290 it would be great if we could add creating a supplier and group to this list to remove the 'Pre-Requisites' task. 
Do you have any plans for this already? If not, I'll get onto it  😄

**Comment by ahdinosaur** [comment]
>  it would be great if we could add creating a supplier and group to this list to remove the 'Pre-Requisites' task.
> Do you have any plans for this already? If not, I'll get onto it 😄

when creating an order, you can choose to create a new consumer or supplier with that order. if you do this, it should then create a pre-reqs task to fill in the details for that new consumer or supplier. this is my best take on a solution for #290, do you have a suggestion for something different than this?

**Comment by danalexilewis** [comment]
@ahdinosaur what’s a consumer in the above? Is it a group?

In regards to the ux of this process I think a good analogy is toggl where you can quick create tags, clients, or projects from the filters. However if you want to set more refined details you need to go to the corresponding management page.

I think this is balancing act of **enabling** peeps to create new groups or suppliers (and products) without **derailing** the order creation process. 

So If a user wishes to add a new group or supplier to the order/system we could think of the tasks we give them in three categories:
 - those that have to be done as part of the order creation workflow, ie extending it. (Eg group name, supplier email)
 - those that have to be done before the order close (eg invite members)
 - those that are optional (eg add group photo)

Another angle we could take for groups is dividing between individual agent tasks and group tasks.

**Comment by ahdinosaur** [comment]
the current progress is merged with #309, will deploy to production to start testing live.

**Pull request closed without merging**
