### PR TITLE
intend the product drop

### LINKED ISSUE #377: product intent component improvements
- on intent page,
  - everyone had to clearly read text, kinda understood, maybe
  - unclear that there was a text input
  - didn't realize you could enter at multiple price points
  - need to communicate
    - what to do on a fixed volume order
      - fix volume @ 1 price, whatever it is -> cheapest unlocked
    - what to do on a fixed budget order
      - fixed budget, get max volume, at price point unlocked
     - what to do on an opportunistic order
       -  'i only want to buy if it's at the cheapest price point'

### PR DESCRIPTION
**Pull request by ahdinosaur**
work in progress to close #377 

trying something like:

screenshot_20180111_161848

### CODE REVIEW

**Comment by ahdinosaur** [comment]
got something!

this is two price specs:

1. minimum of 10, price of 9.99 NZD
2. minimum of 100, price of 7.99 NZD

with collective intents where:

1. has 15
2. has 50

screenshot_20180112_203112

still needs some work, it's confusing which lines mean what, some points hide the view of the progress bars.

**Comment by ahdinosaur** [comment]
okay easy fix to make it usable.

screenshot_20180113_125845

i think i might try adding boxes, kinda like the circles, but under the progress bars, which provide text for each progress bar.

**Comment by ahdinosaur** [comment]
screenshot_20180113_160831

**Comment by ahdinosaur** [comment]
next up, show highest met progress in green, filter out any progress below that point.

**Comment by danalexilewis** [comment]
Looks awesome Mikey!

**Comment by ahdinosaur** [comment]
screenshot_20180114_160130
screenshot_20180114_160142

**Comment by danalexilewis** [comment]
Nice job @ahdinosaur - your a wizard at night and in the day!

**Review by gregorykan — APPROVED** [review]
:+1: stellar job @ahdinosaur !!

**Pull request merged**
