### PR TITLE
Fix/order summary styles

### PR DESCRIPTION
**Pull request by sarah-arrrgh**

### CODE REVIEW

**Comment by sarah-arrrgh** [comment]
@agentlewis what are the contact details of *Ruru Kāhui Ako* that we can add to the mock data on the supplier order summary page for the demo? Do you have them or can we at least make them up to be half-way believable?

I'm thinking
- contact person name
- delivery address
- billing address
- email
- phone (main, mobile etc.)

**Comment by danalexilewis** [comment]
Oh ruru is made up.

Just give it my details for phone number and devacademy address for location

**Comment by sarah-arrrgh** [comment]
TODO:

- [ ] update contact details for Ruru Kāhui Ako in order story (and maybe fix the way i've mocked the data if it's wrong?)
- [ ] export the required contact details from story (unsure exactly what we wanna show on the *supplier order summary* page, y'all can figure that one out!)
- [ ] add contact details to supplier order summary component (there's a beautiful div there as a placeholder currently, you're welcome)

**Comment by michael-smith-nz** [comment]
Added the group and supplier address to the summary, needs styled

**Pull request merged**
