### PR TITLE
god login

### LINKED ISSUE #52: dumb component: god login / signup
https://blog.codinghorror.com/the-god-login/

### PR DESCRIPTION
**Pull request by ahdinosaur**
closes https://github.com/root-systems/cobuy/issues/52

### CODE REVIEW

**Comment by ahdinosaur** [comment]
sign in with...

cobuy

**Comment by ahdinosaur** [comment]
welcome to Cobuy!

cobuy3
cobuy2
cobuy4

**Comment by mischa-s** [comment]
looks divine @ahdinosaur !

**Comment by ahdinosaur** [comment]
self-merged, but feedback still always welcome.

**Pull request merged**
